version: '3.1'
services:

  db:
    container_name: mydb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: bluehorizon
    image: bluehorizon:v1.0
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
    driver: local
